server:
  port: 6060
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: Attendance
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/attendance
    username: root
    password: 1234 # 코딩하는 사람 맞춰서 DB 아이디 및 비밀번호 변경
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
      table-prefix: BATCH_
    job:
      enabled: false
  jpa:
   show-sql: true
   properties:
     hibernate:
       format_sql: true
       show_sql: true

# Debezium 설정
debezium:
  source:
    db:
      name: source_db
      host: localhost
      port: 3306
      username: root
      password: 1234
      database: member 
      table: ceo 
  target:
    db:
      name: target_db
      host: localhost
      port: 3306
      username: root
      password: 1234
      database: attendance 
      table: ceo 
